### ISSUE TITLE
Apple will not accept UIWebView anymore.

### ISSUE THREAD

**Issue by jesus-deepblocks** [juliandramirez/react-native-user-identity#2]
When submitting Apps to Testflight, Apple replies with an email that includes:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs.  See https://developer.apple.com/documentation/uikit/uiwebview for more information.

Now, I was able to track down the `UIWebView`s to this repo (find it too in my Firebase and FBSDK dependencies but just bumping to the latest version fixed it) but strangely enough I can find it anywhere on the code, only in the `myApp/ios/build/` directory. Any help with this issue would be much appreciated as Apple can start rejecting Apps for this reason at any point now (at this point looks like is only a warning).

Thanks in advance.

**Comment by juliandramirez** [comment]
@jesus-deepblocks 

UIWebView is not used anywhere. The module does not have any external dependencies either. I don't think your error is related to this package.

I just updated the project documentation and bumped the version of the example project to the latest RN version as of now (0.61.5). I hope it helps but I would also think it is unrelated.

In any case, let me know if I should reopen this issue

----------------------------------------------------------
UPDATE: Just got an app approved in the app store with this library included.
