### ISSUE TITLE
Build Failed with react native 0.70.0

### ISSUE THREAD

**Issue by 92sajid110** [juliandramirez/react-native-user-identity#28]
Execution failed for task ':react-native-user-identity:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:D:\Sajid\projects\temp\tempApp\node_modules\react-native-user-identity\android\build\intermediates\merged_res\release\values\values.xml:2722: AAPT: error: resource android:attr/lStar not found.

**Comment by juliandramirez** [comment]
will mark it as an issue with your local env unless you update this and will re-open the ticket then
