### ISSUE TITLE
Emphasis "Sign In" instead of "Cancel" for iOS when iosUserConfirmation is true

### ISSUE THREAD

**Issue by robinshin** [juliandramirez/react-native-user-identity#31]
Hello,

First of all thank your for having created and for maintaining this package.

For iOS, when setting iosUserConfirmation to true, the following dialog opens:

[https://raw.githubusercontent.com/juliandramirez/react-native-user-identity/master/docs/img/ios-user-confirmation.png]

Is it possible to write in bold the "Sign In" text instead of the "Cancel" one?

If not, is it possible to unbold the "Cancel" text?

Thanks in advance

**Comment by juliandramirez** [comment]
Hi @robinshin. This is the default behavior for react native alerts; I think it has to do with the apple human interface guidelines,
Refer to this for more info https://developer.apple.com/design/human-interface-guidelines/components/presentation/alerts/
