### ISSUE TITLE
is it possible to change style of prompt dialog on android?

### ISSUE THREAD

**Issue by nikkizol** [juliandramirez/react-native-user-identity#35]
Calling this - `RNUserIdentity.getUserId({});` prompts dialog ,Choose an account' which takes full width of the screen and it has different style then regular `Alert`. any idea how to fix it?
![IMG_5274](https://user-images.githubusercontent.com/45672257/222208390-e34e028e-47ab-44fd-ba43-1b965c363cdd.jpg)

**Comment by juliandramirez** [comment]
The styles are OS-dependent as far as I'm aware of.
On Android, it is defined by the default styling of the modal that is triggered by "android.accounts.AccountManager. newChooseAccountIntent"

If you can find a way to set styles there do let me know.
