### ISSUE TITLE
Expo app crashes when fetchUserIdentity is called

### ISSUE THREAD

**Issue by gusgordon** [juliandramirez/react-native-user-identity#39]
Hello! Thanks for making this package. I am trying to get it to work in my Expo app that I'm building for iOS. I'm calling `getUserId` like this:

```
const fetchUserIdentity = async () => {
    try {
        const result = await RNUserIdentity.getUserId({});
        return result;
    } catch (error) {
        return null;
    }
};
```

where I pass an empty object to `getUserId` because it requires an `options` argument now it seems.

I am also having Expo request iCloud Storage permissions with:
```
"ios": {
    "supportsTablet": true,
    "bundleIdentifier": "com.myname.myapp",
    "entitlements": {
        "com.apple.developer.icloud-container-identifiers": [
            "iCloud.com.myname.myapp"
        ]
    }
}
```
in Expo's app.json file - not sure if this is correct either.

When the `fetchUserIdentity` function above gets executed, my app crashes. Let me know if you have any ideas, thanks.

**Comment by juliandramirez** [comment]
Package does not work on Expo apps. You need to eject the application
